package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/mcabezas/archlang/sdk"
)

func Generate(arch *sdk.Architecture, packageName string) ([]byte, error) {
	var buf bytes.Buffer

	components := arch.Components()
	sort.Slice(components, func(i, j int) bool {
		return qualifiedName(components[i]) < qualifiedName(components[j])
	})

	buf.WriteString("// Code generated by archlang. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", packageName)

	// Type definitions
	buf.WriteString("type ComponentKind string\n\n")
	buf.WriteString("const (\n")
	buf.WriteString("\tKindComponent ComponentKind = \"component\"\n")
	buf.WriteString("\tKindService   ComponentKind = \"service\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("type Component struct {\n")
	buf.WriteString("\tName        string\n")
	buf.WriteString("\tPackage     string\n")
	buf.WriteString("\tKind        ComponentKind\n")
	buf.WriteString("\tDownstreams []*Component\n")
	buf.WriteString("\tUpstreams   []*Component\n")
	buf.WriteString("}\n\n")

	// Variable declarations
	buf.WriteString("var (\n")
	for _, c := range components {
		fmt.Fprintf(&buf, "\t%s = &Component{\n", toGoName(qualifiedName(c)))
		fmt.Fprintf(&buf, "\t\tName: %q,\n", c.Name)
		fmt.Fprintf(&buf, "\t\tPackage: %q,\n", c.Package)
		fmt.Fprintf(&buf, "\t\tKind: Kind%s,\n", toKindName(c.Kind))
		buf.WriteString("\t}\n")
	}
	buf.WriteString(")\n\n")

	// Helper slices
	buf.WriteString("var AllComponents = []*Component{\n")
	for _, c := range components {
		fmt.Fprintf(&buf, "\t%s,\n", toGoName(qualifiedName(c)))
	}
	buf.WriteString("}\n\n")

	services := arch.Services()
	sort.Slice(services, func(i, j int) bool {
		return qualifiedName(services[i]) < qualifiedName(services[j])
	})
	buf.WriteString("var AllServices = []*Component{\n")
	for _, c := range services {
		fmt.Fprintf(&buf, "\t%s,\n", toGoName(qualifiedName(c)))
	}
	buf.WriteString("}\n\n")

	// init() to wire relationships
	buf.WriteString("func init() {\n")
	for _, c := range components {
		varName := toGoName(qualifiedName(c))
		if len(c.Downstreams) > 0 {
			refs := make([]string, len(c.Downstreams))
			for i, ds := range c.Downstreams {
				refs[i] = toGoName(qualifiedName(ds))
			}
			fmt.Fprintf(&buf, "\t%s.Downstreams = []*Component{%s}\n",
				varName, strings.Join(refs, ", "))
		}
		if len(c.Upstreams) > 0 {
			refs := make([]string, len(c.Upstreams))
			for i, us := range c.Upstreams {
				refs[i] = toGoName(qualifiedName(us))
			}
			fmt.Fprintf(&buf, "\t%s.Upstreams = []*Component{%s}\n",
				varName, strings.Join(refs, ", "))
		}
	}
	buf.WriteString("}\n")

	return format.Source(buf.Bytes())
}

func qualifiedName(c *sdk.Component) string {
	return c.Package + "." + c.Name
}

func toGoName(name string) string {
	// Split on dots and hyphens, capitalize each part
	name = strings.ReplaceAll(name, ".", "-")
	parts := strings.Split(name, "-")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func toKindName(kind sdk.ComponentKind) string {
	switch kind {
	case sdk.KindService:
		return "Service"
	default:
		return "Component"
	}
}
