package generator

import (
	"strings"
	"testing"
)

func TestGenerate(t *testing.T) {
	output, err := Generate("../examples/ecommerce", "architecture")
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	code := string(output)

	if !strings.Contains(code, "// Code generated by archlang. DO NOT EDIT.") {
		t.Error("missing generated header")
	}

	if !strings.Contains(code, "package architecture") {
		t.Error("missing package declaration")
	}

	if !strings.Contains(code, `"github.com/mcabezas/archlang/graph"`) {
		t.Error("missing graph import")
	}

	// Check some components are declared as vars
	for _, name := range []string{
		"OrdersOrderManagement",
		"PaymentsPaymentProcessing",
		"UsersAuth",
		"GatewayLoadBalancer",
		"DeliveryTracking",
		"NotificationsEmail",
	} {
		if !strings.Contains(code, name) {
			t.Errorf("missing variable declaration for %s", name)
		}
	}

	// Check service uses NewService with options
	if !strings.Contains(code, "graph.NewService(") {
		t.Error("missing NewService constructor")
	}

	// Check infra uses NewInfra with options
	if !strings.Contains(code, "graph.NewInfra(") {
		t.Error("missing NewInfra constructor")
	}

	// Check WithName and WithDomain are used
	if !strings.Contains(code, "graph.WithName(") {
		t.Error("missing WithName option")
	}
	if !strings.Contains(code, "graph.WithDomain(") {
		t.Error("missing WithDomain option")
	}

	// Check AllGraphs
	if !strings.Contains(code, "var AllGraphs") {
		t.Error("missing AllGraphs declaration")
	}

	// Check AllComponents uses graph.Component
	if !strings.Contains(code, "[]graph.Component") {
		t.Error("missing graph.Component type in slices")
	}

	// Check edge wiring
	if !strings.Contains(code, ".AddDownstream(") {
		t.Error("missing downstream wiring")
	}

	// Check collaboration with features
	if !strings.Contains(code, ".AddCollaboration(") {
		t.Error("missing collaboration wiring")
	}
	if !strings.Contains(code, "graph.Feature{") {
		t.Error("missing Feature type in generated code")
	}

	// Check registration
	if !strings.Contains(code, ".Register(") {
		t.Error("missing node registration")
	}
}

func TestConnectedComponents(t *testing.T) {
	g := &builtGraph{
		nodes: map[string]*graphNode{
			"pkg1.a": {qualifiedName: "pkg1.a", name: "a", domain: "pkg1", isService: true, downstreams: []string{"pkg1.b"}},
			"pkg1.b": {qualifiedName: "pkg1.b", name: "b", domain: "pkg1", isService: true, upstreams: []string{"pkg1.a"}},
			"pkg2.x": {qualifiedName: "pkg2.x", name: "x", domain: "pkg2", isService: true},
		},
		order: []string{"pkg1.a", "pkg1.b", "pkg2.x"},
	}

	components := connectedComponents(g)
	if len(components) != 2 {
		t.Fatalf("expected 2 connected components, got %d", len(components))
	}
}

func TestToGoName(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"users.redis", "UsersRedis"},
		{"gateway.api-gateway", "GatewayApiGateway"},
		{"orders.order-management", "OrdersOrderManagement"},
		{"notifications.push", "NotificationsPush"},
		{"payments/stripe", "PaymentsStripe"},
	}

	for _, tt := range tests {
		got := toGoName(tt.input)
		if got != tt.expected {
			t.Errorf("toGoName(%q) = %q, want %q", tt.input, got, tt.expected)
		}
	}
}
