package generator

import (
	"strings"
	"testing"

	"github.com/mcabezas/archlang/sdk"
)

func TestGenerate(t *testing.T) {
	arch, err := sdk.Compile("../examples/ecommerce")
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	output, err := Generate(arch, "architecture")
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	code := string(output)

	if !strings.Contains(code, "// Code generated by archlang. DO NOT EDIT.") {
		t.Error("missing generated header")
	}

	if !strings.Contains(code, "package architecture") {
		t.Error("missing package declaration")
	}

	// Check all components are declared as vars
	for _, name := range []string{"Redis", "Postgres", "ApiGateway", "Checkout", "Payments", "Users", "Ledger", "Notifications", "Inventory"} {
		if !strings.Contains(code, name+" = &Component{") {
			t.Errorf("missing variable declaration for %s", name)
		}
	}

	// Check kinds
	if !strings.Contains(code, `Kind: KindComponent,`) {
		t.Error("missing KindComponent usage")
	}
	if !strings.Contains(code, `Kind: KindService,`) {
		t.Error("missing KindService usage")
	}

	// Check init wiring
	if !strings.Contains(code, "func init()") {
		t.Error("missing init function")
	}
	if !strings.Contains(code, "Payments.Downstreams") {
		t.Error("missing downstream wiring for Payments")
	}
	if !strings.Contains(code, "Redis.Upstreams") {
		t.Error("missing upstream wiring for Redis")
	}
}

func TestToGoName(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"redis", "Redis"},
		{"api-gateway", "ApiGateway"},
		{"checkout", "Checkout"},
		{"my-cool-service", "MyCoolService"},
	}

	for _, tt := range tests {
		got := toGoName(tt.input)
		if got != tt.expected {
			t.Errorf("toGoName(%q) = %q, want %q", tt.input, got, tt.expected)
		}
	}
}
