package generator

import (
	"strings"
	"testing"

	"github.com/mcabezas/archlang/sdk"
)

func TestGenerate(t *testing.T) {
	arch, err := sdk.Compile("../examples/ecommerce")
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	output, err := Generate(arch, "architecture")
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	code := string(output)

	if !strings.Contains(code, "// Code generated by archlang. DO NOT EDIT.") {
		t.Error("missing generated header")
	}

	if !strings.Contains(code, "package architecture") {
		t.Error("missing package declaration")
	}

	// Check some components are declared as vars with qualified names
	for _, name := range []string{
		"OrdersOrderManagement",
		"PaymentsPaymentProcessing",
		"UsersAuth",
		"GatewayApi",
		"DeliveryTracking",
		"NotificationsEmail",
	} {
		if !strings.Contains(code, name+" = &Component{") {
			t.Errorf("missing variable declaration for %s", name)
		}
	}

	// Check Package field is set
	if !strings.Contains(code, `Package: "orders"`) {
		t.Error("missing Package field for orders")
	}

	// Check kinds
	if !strings.Contains(code, "KindComponent") {
		t.Error("missing KindComponent usage")
	}
	if !strings.Contains(code, "KindService") {
		t.Error("missing KindService usage")
	}

	// Check init wiring
	if !strings.Contains(code, "func init()") {
		t.Error("missing init function")
	}

	// Cross-package wiring: orders.order-management -> payments.payment-processing
	if !strings.Contains(code, "OrdersOrderManagement.Downstreams") {
		t.Error("missing downstream wiring for OrdersOrderManagement")
	}
}

func TestToGoName(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"users.redis", "UsersRedis"},
		{"gateway.api-gateway", "GatewayApiGateway"},
		{"orders.order-management", "OrdersOrderManagement"},
		{"notifications.push", "NotificationsPush"},
	}

	for _, tt := range tests {
		got := toGoName(tt.input)
		if got != tt.expected {
			t.Errorf("toGoName(%q) = %q, want %q", tt.input, got, tt.expected)
		}
	}
}
