package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/mcabezas/archlang/sdk"
)

func Generate(arch *sdk.Architecture, packageName string) ([]byte, error) {
	var buf bytes.Buffer

	components := arch.Components()
	sort.Slice(components, func(i, j int) bool {
		return components[i].Name < components[j].Name
	})

	buf.WriteString("// Code generated by archlang. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// Type definitions
	buf.WriteString("type ComponentKind string\n\n")
	buf.WriteString("const (\n")
	buf.WriteString("\tKindComponent ComponentKind = \"component\"\n")
	buf.WriteString("\tKindService   ComponentKind = \"service\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("type Component struct {\n")
	buf.WriteString("\tName        string\n")
	buf.WriteString("\tKind        ComponentKind\n")
	buf.WriteString("\tDownstreams []*Component\n")
	buf.WriteString("\tUpstreams   []*Component\n")
	buf.WriteString("}\n\n")

	// Variable declarations
	buf.WriteString("var (\n")
	for _, c := range components {
		buf.WriteString(fmt.Sprintf("\t%s = &Component{\n", toGoName(c.Name)))
		buf.WriteString(fmt.Sprintf("\t\tName: %q,\n", c.Name))
		buf.WriteString(fmt.Sprintf("\t\tKind: Kind%s,\n", toKindName(c.Kind)))
		buf.WriteString("\t}\n")
	}
	buf.WriteString(")\n\n")

	// Helper slices
	buf.WriteString("var AllComponents = []*Component{\n")
	for _, c := range components {
		buf.WriteString(fmt.Sprintf("\t%s,\n", toGoName(c.Name)))
	}
	buf.WriteString("}\n\n")

	services := arch.Services()
	sort.Slice(services, func(i, j int) bool {
		return services[i].Name < services[j].Name
	})
	buf.WriteString("var AllServices = []*Component{\n")
	for _, c := range services {
		buf.WriteString(fmt.Sprintf("\t%s,\n", toGoName(c.Name)))
	}
	buf.WriteString("}\n\n")

	// init() to wire relationships
	buf.WriteString("func init() {\n")
	for _, c := range components {
		if len(c.Downstreams) > 0 {
			refs := make([]string, len(c.Downstreams))
			for i, ds := range c.Downstreams {
				refs[i] = toGoName(ds.Name)
			}
			buf.WriteString(fmt.Sprintf("\t%s.Downstreams = []*Component{%s}\n",
				toGoName(c.Name), strings.Join(refs, ", ")))
		}
		if len(c.Upstreams) > 0 {
			refs := make([]string, len(c.Upstreams))
			for i, us := range c.Upstreams {
				refs[i] = toGoName(us.Name)
			}
			buf.WriteString(fmt.Sprintf("\t%s.Upstreams = []*Component{%s}\n",
				toGoName(c.Name), strings.Join(refs, ", ")))
		}
	}
	buf.WriteString("}\n")

	return format.Source(buf.Bytes())
}

func toGoName(name string) string {
	parts := strings.Split(name, "-")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func toKindName(kind sdk.ComponentKind) string {
	switch kind {
	case sdk.KindService:
		return "Service"
	default:
		return "Component"
	}
}
